---
deployment:
  tasks:
    - export DEPLOYPATH=/home/impac3882/karinna.impactadigital.cl
    - /bin/cp -r index.html $DEPLOYPATH/
    - /bin/cp -r portfolio.html shop.html consultoria.html $DEPLOYPATH/
    - /bin/cp -r css $DEPLOYPATH/
    - /bin/cp -r js $DEPLOYPATH/
    - /bin/cp -r assets $DEPLOYPATH/
